name: Codacy Analysis CLI

on: ["push"]

jobs:
  name: Codacy Analysis CLI
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: execute python file # run file
      run: |
        python TestOrchestrator4ML-main/detection/fuzz.py
