name: Run Fuzz File

on: ["push"]

jobs:
  build:
    name: Run Fuzz File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: setup python
        run: |
          python -m pip install --upgrade pip

      - name: execute python file # run file
        run: |
          python TestOrchestrator4ML-main/detection/fuzz.py
